services:
  gateway:
    container_name: gateway
    build:
      context: ./Insurence-microservices
      dockerfile: Dockerfile-gateway
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - grpc

  grpc:
    container_name: grpc
    build:
      context: ./Insurence-microservices
      dockerfile: Dockerfile-grpc
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5435:5432
