services:
  geteway:
    build: insurance-claims-gateway/
    depends_on:
      - grpc
    env_file:
      - .env
  
  grpc:
    build: insurance-claims-grpc/
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
