# Base image
FROM node:lts-alpine

# Project name
ARG APP 

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY --chown=node:node package*.json ./

# Install app dependencies
RUN npm ci

# Bundle app source
COPY --chown=node:node . .

# Creates a "dist" folder with the production build
RUN npm run build common

# Initialize a @prisma/client
RUN npx prisma migrate

# Start the server using the production build
CMD npm run start grpc